package gomega_stub_test

import (
	"fmt"
	. "github.com/CameronHonis/gomega-stub"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

type Object struct {
	FieldA string
}

func NewObject() *Object {
	return &Object{
		FieldA: "fieldA",
	}
}

func (o *Object) GetFieldA() string {
	return o.FieldA
}

func (o *Object) SetFieldA(fieldA string) {
	o.FieldA = fieldA
}

func (o *Object) Add(a, b int) int {
	return a + b
}

func (o *Object) Divide(a, b int) (int, error) {
	if b == 0 {
		return 0, fmt.Errorf("cannot divide by zero")
	}
	return a / b, nil
}

// NOTE: the StubbedObject definition below would be automatically generated by the generator
//	provided by this package. The generator would be run as a separate step in the build process.
//	The generator would also create the constructor and the method overrides on the base struct.
type StubbedObject struct {
	Stubbed[Object]
}

func NewStubbedObject() *StubbedObject {
	so := &StubbedObject{}
	so.Stubbed = *NewStubbed[Object](so, NewObject())
	return so
}

func (s *StubbedObject) GetFieldA() string {
	out := s.Call("GetFieldA")
	return out[0].(string)
}

func (s *StubbedObject) SetFieldA(fieldA string) {
	s.Call("SetFieldA", fieldA)
}

func (s *StubbedObject) Add(a, b int) int {
	out := s.Call("Add", a, b)
	return out[0].(int)
}

func (s *StubbedObject) Divide(a, b int) (int, error) {
	out := s.Call("Divide", a, b)
	return out[0].(int), out[1].(error)
}

func (s *StubbedObject) AddStub(a int) int {
	return 0
}

var _ = Describe("Stubbed", func() {
	var stubbedObject *StubbedObject
	BeforeEach(func() {
		stubbedObject = NewStubbedObject()
	})
	Describe("StubMethod", func() {
		It("adds the method to the stubbed object context", func() {
			methodStub := func(rec *Object) string {
				return "hello"
			}
			stubbedObject.StubMethod("GetFieldA", methodStub)
			Expect(stubbedObject.IsStubbed("GetFieldA")).To(BeTrue())
		})
		When("the method name passed does not exist on the struct", func() {
			It("panics", func() {
				Expect(func() {
					stubbedObject.StubMethod("someNonExistentMethod", func() {})
				}).To(Panic())
			})
		})
		When("the method stub is not typed properly", func() {
			When("the return type is incorrect", func() {
				It("panics", func() {
					Expect(func() {
						stubbedObject.StubMethod("GetFieldA", func() {})
					}).To(Panic())
				})
			})
			When("the number of arguments is incorrect", func() {
				It("panics", func() {
					Expect(func() {
						stubbedObject.StubMethod("Add", func(a int) int {
							return 0
						})
					}).To(Panic())
				})
			})
			When("the argument types are incorrect", func() {
				It("panics", func() {
					Expect(func() {
						stubbedObject.StubMethod("Add", func(a, b string) int {
							return 0
						})
					}).To(Panic())
				})
			})
		})
	})
})
